---
- name: Debug
  debug:
    msg: "Message! {{ package_name }}"
    verbosity: 1

- name: Install package
  win_chocolatey:
    name: "{{ package_name }}"
    state: present
    package_params: "{{ parameters }}"

- name: Enable service
  win_service:
    name: "{{ service_name }}"
    state: started

- name: Create FW rule
  win_firewall_rule:
    name: "{{ service_name }}"
    localport: "{{ local_port }}"
    action: allow
    direction: in
    state: present
    enabled: yes
    protocol: "{{ protocol_name }}"

...

